sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  global:
    - DISPLAY=:99.0
    - API_PORT=8000
    - API_URL=http://localhost:8000/api/v1/
    - SOCKET_HOST=http://localhost:3000/
    - COVERAGE=1

install: npm install

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script: npm test

after_success: bash <(curl -s https://codecov.io/bash)
