version: "2"

services:
  frontend-web:
    container_name: frontend_web
    build: .
    command: npm run standalone
    ports:
      - "8000:8000"
      - "8888:8888"
    environment:
      - API_PORT=8000
      - API_URL=http://localhost:8000/api/v1/
      - PORT=8888